apiVersion: apps/v1beta1
kind: Deployment
metadata: 
  name: httpd
spec: 
  replicas: 3
  template: 
    metadata:
      labels: 
        run: httpd
    spec: 
      containers:
      - name: httpd
        image: httpd
        ports:
        - containerPort: 80
