apiVersion: v1
kind: PersistentVolume
metadata:
  name: asr-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /es/MS_ASR
    server: 10.163.4.18