apiVersion: apps/v1beta1
kind: Deployment
metadata: 
  name: deployment-rollout
spec:
  revisionHistoryLimit: 10
  replicas: 4
  template:
    metadata:
      labels:
        test: httpd
    spec:
      containers:
      - name: httpd-rollout-test
        image: httpd:2.4.33
        ports:
        - containerPort: 80
