apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 4
  template: 
    metadata: 
      labels: 
        app: web_server
    spec: 
      containers:
      - name: nginx
        image: nginx:1.7.9
