apiVersion: v1
kind: PersistentVolume
metadata: 
  name: gysl-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  nfs:
    path: /nfs/gysl-pv
    server: 172.31.3.11
