apiVersion: apps/v1beta1
kind: Deployment
metadata: 
  name: pvc-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: gysl-pvc-app
    spec:
      containers:
      - name: gysl-pvc-container
        image: httpd:2.4.35
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/local/apache2/htdocs
          name: gysl-pvc-test
      volumes:
      - name: gysl-pvc-test
        persistentVolumeClaim: 
          claimName: gysl-pvc
---
apiVersion: v1
kind: Service
metadata: 
  name: gysl-pvc-svc
spec:
  type: NodePort
  selector: 
    run: gysl-pvc-app
  ports: 
  - protocol: TCP
    nodePort: 31888
    port: 8080
    targetPort: 80
