apiVersion: v1
kind: Service
metadata:
  name:  asr
spec:
  selector:
    app:  asr
  type:  NodePort
  ports:
  - name: asr
    protocol: TCP
    port:  34932
    nodePort: 34932
    targetPort:  34932